INSERT INTO USER_DETAILS (ID, BIRTH_DATE, NAME) VALUES (10001, current_date(), 'AJAY MURTEKAR');
INSERT INTO USER_DETAILS (ID, BIRTH_DATE, NAME) VALUES (10002, current_date(), 'ANANDI MURTEKAR');
INSERT INTO USER_DETAILS (ID, BIRTH_DATE, NAME) VALUES (10003, current_date(), 'AVANTI MURTEKAR');
INSERT INTO USER_DETAILS (ID, BIRTH_DATE, NAME) VALUES (10004, current_date(), 'ABHIDNYA MURTEKAR');

INSERT INTO POST(ID, DESCRIPTION, USER_ID) VALUES (20001, 'I want to learn microservices', 10001);
INSERT INTO POST(ID, DESCRIPTION, USER_ID) VALUES (20002, 'I want to learn python', 10001);
INSERT INTO POST(ID, DESCRIPTION, USER_ID) VALUES (20003, 'I want to learn Java', 10002);
INSERT INTO POST(ID, DESCRIPTION, USER_ID) VALUES (20004, 'I want to learn Azure', 10002);