INSERT INTO USER_DETAILS (ID, BIRTH_DATE, NAME) VALUES (1, current_date(), 'AJAY MURTEKAR');
INSERT INTO USER_DETAILS (ID, BIRTH_DATE, NAME) VALUES (2, current_date(), 'ANANDI MURTEKAR');
INSERT INTO USER_DETAILS (ID, BIRTH_DATE, NAME) VALUES (3, current_date(), 'AVANTI MURTEKAR');
INSERT INTO USER_DETAILS (ID, BIRTH_DATE, NAME) VALUES (4, current_date(), 'ABHIDNYA MURTEKAR');